#!/usr/bin/env python3
"""Is the live schema the one the migrations describe?

    python scripts/check-schema-drift.py

Run this *after* `python -m app.bootstrap`, not after `alembic upgrade head`.
The two diverged: startup applied its own DDL after the migrations and dropped
an index the models declare, so a database reporting itself at head failed a
drift check. Calling Alembic directly could never have seen that, which is why
CI checked the wrong thing for as long as it did.

Three questions, in order:

  1. Is the database at the migration head?
  2. Does `alembic check` find nothing to generate?
  3. Do the indexes the models declare actually exist?

The third looks redundant after the second and is not: autogenerate compares
what it can reflect, and an index dropped by something outside Alembic is
exactly the case worth naming explicitly.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _console import force_utf8  # noqa: E402

BACKEND = Path(__file__).resolve().parent.parent / "backend"


def main() -> int:
    force_utf8()
    sys.path.insert(0, str(BACKEND))
    os.chdir(BACKEND)

    from alembic import command
    from alembic.config import Config
    from alembic.script import ScriptDirectory
    from sqlalchemy import create_engine, inspect

    url = os.environ.get("DATABASE_URL_SYNC")
    if not url:
        print("DATABASE_URL_SYNC is not set", file=sys.stderr)
        return 2

    config = Config(str(BACKEND / "alembic.ini"))
    head = ScriptDirectory.from_config(config).get_current_head()

    engine = create_engine(url)
    with engine.connect() as connection:
        current = connection.exec_driver_sql(
            "select version_num from alembic_version").scalar()
    print(f"  head    : {head}")
    print(f"  current : {current}")
    if current != head:
        print(f"\nthe database is at {current!r}, not the head {head!r}", file=sys.stderr)
        return 1

    try:
        command.check(config)
        print("  drift   : none")
    except Exception as exc:  # noqa: BLE001 - alembic raises AutogenerateDiffsDetected
        print(f"\nalembic check failed: {exc}", file=sys.stderr)
        return 1

    # The indexes the models declare, asserted by name against the database.
    from app.core.db import Base
    import app.models  # noqa: F401 - registers every table on Base.metadata

    inspector = inspect(engine)
    missing: list[str] = []
    for table in Base.metadata.sorted_tables:
        if not inspector.has_table(table.name):
            missing.append(f"table {table.name}")
            continue
        present = {index["name"] for index in inspector.get_indexes(table.name)}
        for index in table.indexes:
            if index.name not in present:
                missing.append(f"{table.name}.{index.name}")

    if missing:
        print("\nindexes the models declare but the database does not have:",
              file=sys.stderr)
        for name in missing:
            print(f"  - {name}", file=sys.stderr)
        print("\nSomething outside Alembic changed this schema. Startup DDL is "
              "the usual cause.", file=sys.stderr)
        return 1
    print("  indexes : all declared indexes exist")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
