"""baseline schema as shipped

Revision ID: 2fc7499a99b9
Revises: 
Created: 2026-08-23 05:43:25.684772
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2fc7499a99b9'
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.Enum('USER', 'SYSTEM', 'API', name='actor_type'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_label', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('resource_name', sa.String(length=255), nullable=True),
    sa.Column('result', sa.Enum('SUCCESS', 'FAILURE', name='audit_result'), nullable=False),
    sa.Column('before_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_workspace_id'), 'audit_events', ['workspace_id'], unique=False)
    op.create_index('ix_audit_resource', 'audit_events', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_ws_created', 'audit_events', ['workspace_id', 'created_at'], unique=False)
    op.create_table('connector_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connector_key', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('connector_type', sa.Enum('SOURCE', 'DESTINATION', name='connector_type'), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('documentation_url', sa.String(length=500), nullable=True),
    sa.Column('docker_repository', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('latest_version', sa.String(length=64), nullable=True),
    sa.Column('release_stage', sa.String(length=32), nullable=False),
    sa.Column('support_level', sa.String(length=32), server_default='community', nullable=False),
    sa.Column('engine_definition_id', sa.String(length=120), nullable=True),
    sa.Column('supports_oauth', sa.Boolean(), nullable=False),
    sa.Column('supports_incremental', sa.Boolean(), nullable=False),
    sa.Column('supports_cdc', sa.Boolean(), nullable=False),
    sa.Column('supports_namespaces', sa.Boolean(), nullable=False),
    sa.Column('supported_destination_sync_modes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('spec_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('declarative_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('display_version', sa.String(length=64), nullable=True),
    sa.Column('owner_workspace_id', sa.UUID(), nullable=True),
    sa.Column('spec_hash', sa.String(length=64), nullable=True),
    sa.Column('spec_source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', 'DEPRECATED', name='connector_status'), nullable=False),
    sa.Column('certification', sa.Enum('SUPPORTED', 'BETA', 'HIDDEN', 'BLOCKED', name='connector_certification'), nullable=False),
    sa.Column('disabled_reason', sa.Text(), nullable=True),
    sa.Column('image_pulled', sa.Boolean(), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connector_definitions')),
    sa.UniqueConstraint('connector_key', name='uq_connector_key')
    )
    op.create_index(op.f('ix_connector_definitions_connector_key'), 'connector_definitions', ['connector_key'], unique=False)
    op.create_index(op.f('ix_connector_definitions_connector_type'), 'connector_definitions', ['connector_type'], unique=False)
    op.create_index(op.f('ix_connector_definitions_display_name'), 'connector_definitions', ['display_name'], unique=False)
    op.create_index(op.f('ix_connector_definitions_owner_workspace_id'), 'connector_definitions', ['owner_workspace_id'], unique=False)
    op.create_table('engine_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('engine_type', sa.Enum('AIRBYTE_EMBEDDED', 'AIRBYTE_API', name='engine_type'), nullable=False),
    sa.Column('base_url_ref', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('adapter_contract_version', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('HEALTHY', 'DEGRADED', 'OFFLINE', 'UNKNOWN', name='engine_status'), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('capacity_class', sa.String(length=32), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_engine_instances'))
    )
    op.create_table('operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('SOURCE_CHECK', 'DESTINATION_CHECK', 'DISCOVER', 'CATALOG_REFRESH', 'CONNECTOR_PULL', name='operation_kind'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', name='operation_status'), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('progress_message', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operations'))
    )
    op.create_index(op.f('ix_operations_workspace_id'), 'operations', ['workspace_id'], unique=False)
    op.create_index('ix_operations_ws_created', 'operations', ['workspace_id', 'created_at'], unique=False)
    op.create_table('secrets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('wrapped_data_key', sa.Text(), nullable=False),
    sa.Column('ciphertext', sa.Text(), nullable=False),
    sa.Column('field_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secrets'))
    )
    op.create_index(op.f('ix_secrets_ref'), 'secrets', ['ref'], unique=True)
    op.create_index(op.f('ix_secrets_workspace_id'), 'secrets', ['workspace_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('engine_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('product_resource_type', sa.Enum('SOURCE', 'DESTINATION', 'PIPELINE', 'RUN', name='product_resource_type'), nullable=False),
    sa.Column('product_resource_id', sa.UUID(), nullable=False),
    sa.Column('engine_instance_id', sa.UUID(), nullable=True),
    sa.Column('engine_type', sa.Enum('AIRBYTE_EMBEDDED', 'AIRBYTE_API', name='engine_type'), nullable=False),
    sa.Column('engine_resource_type', sa.Enum('SOURCE', 'DESTINATION', 'CONNECTION', 'JOB', name='engine_resource_type'), nullable=False),
    sa.Column('engine_resource_ref', sa.String(length=512), nullable=False),
    sa.Column('engine_version', sa.String(length=64), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engine_instance_id'], ['engine_instances.id'], name=op.f('fk_engine_mappings_engine_instance_id_engine_instances')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_engine_mappings')),
    sa.UniqueConstraint('product_resource_type', 'product_resource_id', 'engine_resource_type', name='uq_engine_mapping_resource')
    )
    op.create_index('ix_engine_mappings_ws', 'engine_mappings', ['workspace_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', name='workspace_status'), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('engine_instance_id', sa.UUID(), nullable=True),
    sa.Column('engine_workspace_ref', sa.String(length=255), nullable=True),
    sa.Column('allow_save_without_test', sa.Boolean(), nullable=False),
    sa.Column('auto_accept_additive_schema', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engine_instance_id'], ['engine_instances.id'], name=op.f('fk_workspaces_engine_instance_id_engine_instances')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_table('alert_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('event_type', sa.Enum('RUN_FAILED', 'CONSECUTIVE_FAILURES', 'SOURCE_AUTH_ERROR', 'DESTINATION_ERROR', 'SCHEMA_BREAKING_CHANGE', 'FRESHNESS_BREACH', 'ENGINE_DEGRADED', name='alert_event_type'), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'EMAIL', 'WEBHOOK', name='alert_channel'), nullable=False),
    sa.Column('channel_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_alert_rules_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rules'))
    )
    op.create_index(op.f('ix_alert_rules_workspace_id'), 'alert_rules', ['workspace_id'], unique=False)
    op.create_index('ix_alert_rules_ws_event', 'alert_rules', ['workspace_id', 'event_type'], unique=False)
    op.create_table('builder_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('connector_key', sa.String(length=120), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='builder_status'), nullable=False),
    sa.Column('published_version', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_ok', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_builder_projects_created_by_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_builder_projects_updated_by_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_builder_projects_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_builder_projects'))
    )
    op.create_index(op.f('ix_builder_projects_connector_key'), 'builder_projects', ['connector_key'], unique=False)
    op.create_index(op.f('ix_builder_projects_workspace_id'), 'builder_projects', ['workspace_id'], unique=False)
    op.create_index('ix_builder_ws_status', 'builder_projects', ['workspace_id', 'status'], unique=False)
    op.create_index('uq_builder_ws_name_live', 'builder_projects', ['workspace_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('destinations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('connector_key', sa.String(length=120), nullable=False),
    sa.Column('connector_version', sa.String(length=64), nullable=True),
    sa.Column('configuration_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secret_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', 'DELETE_PENDING', 'DELETED', 'ERROR', name='resource_status'), nullable=False),
    sa.Column('health_status', sa.Enum('HEALTHY', 'WARNING', 'ERROR', 'UNKNOWN', name='health_level'), nullable=False),
    sa.Column('health_code', sa.String(length=64), nullable=True),
    sa.Column('health_message', sa.Text(), nullable=True),
    sa.Column('last_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_result', sa.Enum('PASSED', 'FAILED', 'NOT_TESTED', name='test_result'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_destinations_created_by_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_destinations_updated_by_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_destinations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_destinations'))
    )
    op.create_index(op.f('ix_destinations_workspace_id'), 'destinations', ['workspace_id'], unique=False)
    op.create_index('ix_destinations_ws_connector', 'destinations', ['workspace_id', 'connector_key'], unique=False)
    op.create_index('ix_destinations_ws_status', 'destinations', ['workspace_id', 'status'], unique=False)
    op.create_index('uq_destination_ws_name_live', 'destinations', ['workspace_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'DATA_ADMIN', 'OPERATOR', 'ANALYST', 'AUDITOR', 'PLATFORM_ADMIN', name='member_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_memberships_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_membership_ws_user')
    )
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_memberships_workspace_id'), 'memberships', ['workspace_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('connector_key', sa.String(length=120), nullable=False),
    sa.Column('connector_version', sa.String(length=64), nullable=True),
    sa.Column('configuration_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secret_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', 'DELETE_PENDING', 'DELETED', 'ERROR', name='resource_status'), nullable=False),
    sa.Column('health_status', sa.Enum('HEALTHY', 'WARNING', 'ERROR', 'UNKNOWN', name='health_level'), nullable=False),
    sa.Column('health_code', sa.String(length=64), nullable=True),
    sa.Column('health_message', sa.Text(), nullable=True),
    sa.Column('last_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_result', sa.Enum('PASSED', 'FAILED', 'NOT_TESTED', name='test_result'), nullable=False),
    sa.Column('active_schema_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('discover_locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_sources_created_by_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_sources_updated_by_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_sources_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    op.create_index(op.f('ix_sources_workspace_id'), 'sources', ['workspace_id'], unique=False)
    op.create_index('ix_sources_ws_connector', 'sources', ['workspace_id', 'connector_key'], unique=False)
    op.create_index('ix_sources_ws_status', 'sources', ['workspace_id', 'status'], unique=False)
    op.create_index('uq_source_ws_name_live', 'sources', ['workspace_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('RUN_FAILED', 'CONSECUTIVE_FAILURES', 'SOURCE_AUTH_ERROR', 'DESTINATION_ERROR', 'SCHEMA_BREAKING_CHANGE', 'FRESHNESS_BREACH', 'ENGINE_DEGRADED', name='alert_event_type'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('resource_type', sa.Enum('SOURCE', 'DESTINATION', 'PIPELINE', 'RUN', name='product_resource_type'), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('remediation_action', sa.String(length=64), nullable=True),
    sa.Column('dedup_key', sa.String(length=200), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ACKNOWLEDGED', 'RESOLVED', name='notification_status'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], name=op.f('fk_notifications_rule_id_alert_rules'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_dedup', 'notifications', ['dedup_key', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_workspace_id'), 'notifications', ['workspace_id'], unique=False)
    op.create_index('ix_notifications_ws_status_created', 'notifications', ['workspace_id', 'status', 'created_at'], unique=False)
    op.create_table('schema_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('catalog_hash', sa.String(length=64), nullable=False),
    sa.Column('normalized_catalog', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stream_count', sa.Integer(), nullable=False),
    sa.Column('connector_version', sa.String(length=64), nullable=True),
    sa.Column('discovered_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_schema_snapshots_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schema_snapshots'))
    )
    op.create_index('ix_schema_snapshots_source_time', 'schema_snapshots', ['source_id', 'discovered_at'], unique=False)
    op.create_index(op.f('ix_schema_snapshots_workspace_id'), 'schema_snapshots', ['workspace_id'], unique=False)
    op.create_table('pipelines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'NEEDS_REVIEW', 'DELETE_PENDING', 'DELETED', name='pipeline_status'), nullable=False),
    sa.Column('needs_review_reason', sa.Text(), nullable=True),
    sa.Column('schedule_type', sa.Enum('MANUAL', 'INTERVAL', 'DAILY', 'CRON', name='schedule_type'), nullable=False),
    sa.Column('schedule_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('overlap_policy', sa.Enum('SKIP_IF_RUNNING', 'QUEUE', name='overlap_policy'), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_schema_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('namespace_format', sa.String(length=120), nullable=True),
    sa.Column('stream_prefix', sa.String(length=64), nullable=True),
    sa.Column('last_run_id', sa.UUID(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('sync_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generation_id', sa.Integer(), nullable=False),
    sa.Column('sync_counter', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['active_schema_snapshot_id'], ['schema_snapshots.id'], name=op.f('fk_pipelines_active_schema_snapshot_id_schema_snapshots')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_pipelines_created_by_users')),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], name=op.f('fk_pipelines_destination_id_destinations')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_pipelines_source_id_sources')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_pipelines_updated_by_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_pipelines_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipelines'))
    )
    op.create_index('ix_pipelines_next_run', 'pipelines', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_pipelines_workspace_id'), 'pipelines', ['workspace_id'], unique=False)
    op.create_index('ix_pipelines_ws_destination', 'pipelines', ['workspace_id', 'destination_id'], unique=False)
    op.create_index('ix_pipelines_ws_source', 'pipelines', ['workspace_id', 'source_id'], unique=False)
    op.create_index('ix_pipelines_ws_status', 'pipelines', ['workspace_id', 'status'], unique=False)
    op.create_index('uq_pipeline_ws_name_live', 'pipelines', ['workspace_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('engine_job_ref', sa.String(length=255), nullable=True),
    sa.Column('trigger_type', sa.Enum('MANUAL', 'SCHEDULE', 'RETRY', 'SYSTEM', name='trigger_type'), nullable=False),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('retry_of_run_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'STARTING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'FAILED_TO_START', 'CANCEL_REQUESTED', 'CANCELLED', 'TIMED_OUT', name='run_status'), nullable=False),
    sa.Column('queue_reason', sa.String(length=120), nullable=True),
    sa.Column('error_category', sa.Enum('AUTHENTICATION', 'NETWORK', 'PERMISSION', 'CONFIGURATION', 'SCHEMA', 'RATE_LIMIT', 'DESTINATION_WRITE', 'SOURCE_READ', 'ENGINE', 'CANCELLED', 'VALIDATION', 'CONFLICT', 'NOT_FOUND', 'QUOTA', 'TIMEOUT', 'UNKNOWN', name='error_category'), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('remediation_action', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_synced', sa.BigInteger(), nullable=True),
    sa.Column('bytes_synced', sa.BigInteger(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('technical_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('claimed_by', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], name=op.f('fk_pipeline_runs_pipeline_id_pipelines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retry_of_run_id'], ['pipeline_runs.id'], name=op.f('fk_pipeline_runs_retry_of_run_id_pipeline_runs')),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], name=op.f('fk_pipeline_runs_triggered_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_runs'))
    )
    op.create_index(op.f('ix_pipeline_runs_idempotency_key'), 'pipeline_runs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_workspace_id'), 'pipeline_runs', ['workspace_id'], unique=False)
    op.create_index('ix_runs_status_started', 'pipeline_runs', ['status', 'started_at'], unique=False)
    op.create_index('ix_runs_ws_created', 'pipeline_runs', ['workspace_id', 'created_at'], unique=False)
    op.create_index('ix_runs_ws_pipeline_started', 'pipeline_runs', ['workspace_id', 'pipeline_id', 'started_at'], unique=False)
    op.create_table('pipeline_streams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('namespace', sa.String(length=200), nullable=True),
    sa.Column('stream_name', sa.String(length=300), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('sync_mode', sa.Enum('FULL_REFRESH', 'INCREMENTAL', name='sync_mode'), nullable=False),
    sa.Column('destination_sync_mode', sa.Enum('OVERWRITE', 'APPEND', 'APPEND_DEDUP', name='destination_sync_mode'), nullable=False),
    sa.Column('cursor_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('primary_key_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selected_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('json_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_hash', sa.String(length=64), nullable=True),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], name=op.f('fk_pipeline_streams_pipeline_id_pipelines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_streams')),
    sa.UniqueConstraint('pipeline_id', 'namespace', 'stream_name', name='uq_pipeline_stream')
    )
    op.create_index(op.f('ix_pipeline_streams_pipeline_id'), 'pipeline_streams', ['pipeline_id'], unique=False)
    op.create_table('pipeline_stream_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('namespace', sa.String(length=200), nullable=True),
    sa.Column('stream_name', sa.String(length=300), nullable=False),
    sa.Column('records_emitted', sa.BigInteger(), nullable=False),
    sa.Column('bytes_emitted', sa.BigInteger(), nullable=False),
    sa.Column('sync_mode', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], name=op.f('fk_pipeline_stream_stats_run_id_pipeline_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_stream_stats'))
    )
    op.create_index('ix_stream_stats_run', 'pipeline_stream_stats', ['run_id'], unique=False)
    op.create_table('run_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'STARTING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'FAILED_TO_START', 'CANCEL_REQUESTED', 'CANCELLED', 'TIMED_OUT', name='run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_synced', sa.BigInteger(), nullable=True),
    sa.Column('bytes_synced', sa.BigInteger(), nullable=True),
    sa.Column('failure_summary', sa.Text(), nullable=True),
    sa.Column('log_path', sa.String(length=400), nullable=True),
    sa.Column('engine_attempt_ref', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], name=op.f('fk_run_attempts_run_id_pipeline_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_attempts'))
    )
    op.create_index('ix_attempts_run', 'run_attempts', ['run_id', 'attempt_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attempts_run', table_name='run_attempts')
    op.drop_table('run_attempts')
    op.drop_index('ix_stream_stats_run', table_name='pipeline_stream_stats')
    op.drop_table('pipeline_stream_stats')
    op.drop_index(op.f('ix_pipeline_streams_pipeline_id'), table_name='pipeline_streams')
    op.drop_table('pipeline_streams')
    op.drop_index('ix_runs_ws_pipeline_started', table_name='pipeline_runs')
    op.drop_index('ix_runs_ws_created', table_name='pipeline_runs')
    op.drop_index('ix_runs_status_started', table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_workspace_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_idempotency_key'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index('uq_pipeline_ws_name_live', table_name='pipelines', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_pipelines_ws_status', table_name='pipelines')
    op.drop_index('ix_pipelines_ws_source', table_name='pipelines')
    op.drop_index('ix_pipelines_ws_destination', table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_workspace_id'), table_name='pipelines')
    op.drop_index('ix_pipelines_next_run', table_name='pipelines')
    op.drop_table('pipelines')
    op.drop_index(op.f('ix_schema_snapshots_workspace_id'), table_name='schema_snapshots')
    op.drop_index('ix_schema_snapshots_source_time', table_name='schema_snapshots')
    op.drop_table('schema_snapshots')
    op.drop_index('ix_notifications_ws_status_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_workspace_id'), table_name='notifications')
    op.drop_index('ix_notifications_dedup', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('uq_source_ws_name_live', table_name='sources', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_sources_ws_status', table_name='sources')
    op.drop_index('ix_sources_ws_connector', table_name='sources')
    op.drop_index(op.f('ix_sources_workspace_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_memberships_workspace_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index('uq_destination_ws_name_live', table_name='destinations', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_destinations_ws_status', table_name='destinations')
    op.drop_index('ix_destinations_ws_connector', table_name='destinations')
    op.drop_index(op.f('ix_destinations_workspace_id'), table_name='destinations')
    op.drop_table('destinations')
    op.drop_index('uq_builder_ws_name_live', table_name='builder_projects', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_builder_ws_status', table_name='builder_projects')
    op.drop_index(op.f('ix_builder_projects_workspace_id'), table_name='builder_projects')
    op.drop_index(op.f('ix_builder_projects_connector_key'), table_name='builder_projects')
    op.drop_table('builder_projects')
    op.drop_index('ix_alert_rules_ws_event', table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_workspace_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index('ix_engine_mappings_ws', table_name='engine_mappings')
    op.drop_table('engine_mappings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_secrets_workspace_id'), table_name='secrets')
    op.drop_index(op.f('ix_secrets_ref'), table_name='secrets')
    op.drop_table('secrets')
    op.drop_index('ix_operations_ws_created', table_name='operations')
    op.drop_index(op.f('ix_operations_workspace_id'), table_name='operations')
    op.drop_table('operations')
    op.drop_table('engine_instances')
    op.drop_index(op.f('ix_connector_definitions_owner_workspace_id'), table_name='connector_definitions')
    op.drop_index(op.f('ix_connector_definitions_display_name'), table_name='connector_definitions')
    op.drop_index(op.f('ix_connector_definitions_connector_type'), table_name='connector_definitions')
    op.drop_index(op.f('ix_connector_definitions_connector_key'), table_name='connector_definitions')
    op.drop_table('connector_definitions')
    op.drop_index('ix_audit_ws_created', table_name='audit_events')
    op.drop_index('ix_audit_resource', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_workspace_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
